### ISSUE TITLE
the input/output is super buggy and doesnt even work correctly

### ISSUE THREAD

**Issue by joshbedo** [lh4111/tinypng-cli#1]
doesnt even pickup directories correctly i see them in command line but it says they dont exist

error after it does some images it just breaks.
```
/Users/joshbedo/.nvm/versions/node/v9.2.0/lib/node_modules/tinypng-unlimited-cli/index.js:49
      request(body.output.url)
                          ^
```

**Comment by lh4111** [comment]
It may be caused by uploading too many files at once.


The code was written a year ago and there is no guarantee that it will work correctly.
If I have time, I will try to fix it.
